version: "3.3"
services:
  nginx_proxy:
    image: ${DOCKERHUB_NGINX_IMAGE_NAME}
    ports:
      - 80:80
      - 443:443
    networks:
      - inter_container
  api_server:
    image: ${DOCKERHUB_API_IMAGE_NAME}
    expose:
      - 3000
    environment:
      - GIN_MODE=release
      - PORT=3000
      - MONGO_USERNAME=${MONGODB_USERNAME}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_CLUSTER_ID=${MONGODB_DATABASE}
    restart: "always"
    networks:
      - inter_container
networks:
  inter_container:
